checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/05-19-09AM-21-39/epoch=0737-loss=0.02768.ckpt

OPTION: 1

eval_output_path: log/ours/

t5_max_sentence_length: 512

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144         # 2 ^ 18

number_of_trial: 20
